### ISSUE TITLE
zap does not logs error on logz.io

### ISSUE THREAD

**Issue by himanshuPH** [dougEfresh/zapz#1]
Hey,
I am using zapz with gin framework for logging on logz.io and this is a demo code : 

```
func main() {
	r := gin.New()

	r.Use(gin.Recovery())

	logger, err := zapz.New("token")

	if err != nil {
		panic(err)
	}

		logger.Info("A")
		logger.Info("B")
	
	
	r.GET("/ping1", func(c *gin.Context) {
		logger.Info("C")
		c.String(200, "pong1 "+fmt.Sprint(time.Now().Unix()))
		return
	})

	r.GET("/ping2", func(c *gin.Context) {
		logger.Info("D")
		c.String(200, "pong2 "+fmt.Sprint(time.Now().Unix()))
	})

	r.Run(":8080")
 }

```
So here `A` and `B` will be logged on logz.io but not `C` & `D`.
Is there anything that I am missing in here ?

**Comment by dougEfresh** [comment]
What happens when you use WithDebug option in zapz.New ?

**Comment by himanshuPH** [comment]
Ok so I have added `zapz.WithDebug(os.Stderr)` and for `A` and `B` it says something like this :
```
logziosender.go: Adding item 1 with size 90 (total buffSize: 90)
logziosender.go: Adding item 2 with size 91 (total buffSize: 181)
queue state: goque: Stack or queue is empty
Logz.io: Dropping logs, as FS used space on <path> is 89.79313 percent, and the drop threshold is 70 percent
logziosender.go: draining queue
```

but for `C` and `D` they are never added

**Comment by dougEfresh** [comment]
There is a detection of used disk space, which is at 70 percent. if you are above threshold then logs will drop. 
https://github.com/dougEfresh/logzio-go/blob/master/logziosender.go

**Comment by dougEfresh** [comment]
Added a NewLogz init method which you can pass a LogzioSender, thereby disable or increase diskspace threshold

**Comment by himanshuPH** [comment]
> There is a detection of used disk space, which is at 70 percent. if you are above threshold then logs will drop.
> https://github.com/dougEfresh/logzio-go/blob/master/logziosender.go

thanks for clarifying
